base-url=http>//localhost:5173

spring.data.mongodb.uri=mongodb://127.0.0.1:27017/echotranscribe
spring.application.name=demo

spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.password=
spring.cache.type=redis

# spring.security.oauth2.client.registration.auth0.client-id=RleGcfrO8srQR61QoWbbMzvCBfj3fj7n
# spring.security.oauth2.client.registration.auth0.client-secret=-sQdq11PAHLvbtEtxE-9rpT1yMN5ouW-97MS_yXmysvmXfCz-xD7_mPim0utLuON
# spring.security.oauth2.client.registration.auth0.scope=openid, profile, email
# spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
# spring.security.oauth2.client.registration.auth0.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-jdtdmvnllnhe51fm.us.auth0.com/

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-jdtdmvnllnhe51fm.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://echo.transcribe.api.com/

auth0.domain: dev-jdtdmvnllnhe51fm.us.auth0.com
auth0.client-id: ljNLE3q9awMtkR6DRkaZ4TFXkzR3WDo8
auth0.client-secret: o9xxwptrpdhCvItntBwDbOKrhEQj-TR9MMURnB2mOrwEF7v1e8h1PKnOQShpg9Z_
auth0.audience: https://dev-jdtdmvnllnhe51fm.us.auth0.com/api/v2/

gcloud.bucket-name: echotranscribe-first-bucket
gcloud.location: eu
gcloud.project-id: echotranscribe
gcloud.model-speech-to-text: chirp_3

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=550MB
spring.servlet.multipart.location=/tmp