spring.data.mongodb.uri=mongodb://127.0.0.1:27017/echotranscribe
spring.application.name=demo

spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.password=
spring.cache.type=redis

# spring.security.oauth2.client.registration.auth0.client-id=RleGcfrO8srQR61QoWbbMzvCBfj3fj7n
# spring.security.oauth2.client.registration.auth0.client-secret=-sQdq11PAHLvbtEtxE-9rpT1yMN5ouW-97MS_yXmysvmXfCz-xD7_mPim0utLuON
# spring.security.oauth2.client.registration.auth0.scope=openid, profile, email
# spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
# spring.security.oauth2.client.registration.auth0.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-jdtdmvnllnhe51fm.us.auth0.com/

spring.security.oauth2.resourceserver.jwt.issuer-uri=dev-jdtdmvnllnhe51fm.us.auth0.com
spring.security.oauth2.resourceserver.jwt.audience=https://echo.transcribe.api.com/